<?php

namespace AppBundle\Repository;

use AppBundle\Entity\ApiUser;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityManagerInterface;

/**
 * ApiUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApiUserRepository
{
    protected $entityManger;

    function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManger = $entityManager;
    }

    public function save(ApiUser $user)
    {
        $this->entityManger->persist($user);
        $this->entityManger->flush();
    }

    public function getUserByUsername($username)
    {
        $builder = $this->entityManger->createQueryBuilder();
        $query = $builder->select('user')
            ->from('AppBundle:ApiUser', 'user')
            ->where('user.username = :username')
            ->setParameter('username', $username)
            ->getQuery();

        return $query->getOneOrNullResult();
    }
}
