<?php

namespace AppBundle\Repository;

use AppBundle\Entity\ApiUser;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityManagerInterface;

/**
 * ApiUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApiUserRepository
{
    protected $entityManger;

    function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManger = $entityManager;
    }

    public function save(ApiUser $user)
    {
        $this->entityManger->persist($user);
        $this->entityManger->flush();
    }
}
