<?php

namespace AppBundle\Repository;

/**
 * CoffeeOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoffeeOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
