<?php

namespace AppBundle\Repository;

/**
 * CoffeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoffeeRepository extends \Doctrine\ORM\EntityRepository
{
}
