<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Coffee;
use Doctrine\ORM\EntityManagerInterface;

/**
 * CoffeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoffeeRepository
{
    protected $entityManger;

    function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManger = $entityManager;
    }

    public function save(Coffee $coffee)
    {
        $this->entityManger->persist($coffee);
        $this->entityManger->flush();
    }

    public function remove(Coffee $coffee)
    {
        $this->entityManger->remove($coffee);
        $this->entityManger->flush();
    }

    public function getAllCoffees()
    {
        $builder = $this->entityManger->createQueryBuilder();

        $query = $builder->select('coffee')
            ->from('AppBundle:Coffee', 'coffee')
            ->getQuery();

        return $query->getResult();
    }

    public function getCoffeeById($id)
    {
        $builder = $this->entityManger->createQueryBuilder();

        $query = $builder->select('coffee')
            ->from('AppBundle:Coffee', 'coffee')
            ->where('coffee.id = :id')
            ->setParameter('id', $id)
            ->getQuery();

        return $query->getOneOrNullResult();
    }
}
